### PR TITLE
First attempt at fixing SpaceAfter for punctuation

### PR DESCRIPTION
**Pull request by qipeng**
This is an initial attempt at fixing `SpaceAfter` annotations around punctuation, issue reported in #4 .

### CODE REVIEW

**Comment by dan-zeman** [comment]
Thanks, I have to figure out how to review it. The change is too large and Github will not show the diff.

On a more general note: I agree that it would be useful to detokenize the text, even if it has to be done using heuristics. However, the README of this treebank says "Contributing: elsewhere", which means that any changes made directly in the UD Github repo will be overwritten the next time when an update is performed from the source data outside UD. Ideally, @liljao should review the changes too, and suggest the most suitable way of integrating them into the source version of the treebank.

**Comment by qipeng** [comment]
Thanks for getting back to me @dan-zeman! What I did was basically de-tokenizing the text (from joining tokens with spaces), then aligning the tokens in the CoNLL-U with it. So it should be relatively easy to do programmatically. I can also try to dig up and clean the code I used for this and share with @liljao and everyone else in the UD community should that be useful!

**Comment by dan-zeman** [comment]
Looks good to me.

**Review by dan-zeman — APPROVED** [review]

**Comment by liljao** [comment]
I am very sorry about chiming in so late here! Somehow your previous issue @qipeng went under the radar. 
In fact, the previous versions of this treebank had SpaceAfter-annotation, so probably something has gone wrong during the conversion. I will look into it and get back to you asap.

**Comment by liljao** [comment]
@qipeng @dan-zeman I have now fixed the bug and re-introduced the SpaceAfter-annotation. I prefer this version since it has been aligned with the original, raw texts that were used to create the treebank.

**Comment by dan-zeman** [comment]
Great, thanks!

**Pull request merged**
